MP_STATEMENT = 'deputado_intervencao'
GOV_STATEMENT = 'governo_intervencao'
PM_STATEMENT = 'pm_intervencao'
MINISTER_STATEMENT = 'ministro_intervencao'
STATE_SECRETARY_STATEMENT = 'secestado_intervencao'
PRESIDENT_STATEMENT = 'presidente'
SECRETARY_STATEMENT = 'secretario'
STATEMENT = 'intervencao'

MP_ASIDE = 'deputado_aparte'
VOICES_ASIDE = 'vozes_aparte'
APPLAUSE = 'aplauso'
PROTEST = 'protesto'
LAUGHTER = 'riso'
PAUSE = 'pausa'
VOTE = 'voto'
TIME = 'hora'
NOTE = 'nota'
SILENCE = 'silencio'
INTERRUPTIONS = (VOICES_ASIDE, MP_ASIDE, APPLAUSE, PROTEST, LAUGHTER, PAUSE, VOTE, TIME, NOTE, SILENCE)

DATE = 'data'
DOCUMENT_START = 'inicio_documento'
DOCUMENT = 'documento'
VOTE_STATEMENT_START = 'inicio_declaracao_voto'
VOTE_STATEMENT = 'declaracao_voto'
SEPARATOR = 'separador'
OTHER = 'outro'

PRESIDENT_NAME = 'nome_presidente'
SECRETARY_NAME = 'nomes_secretarios'

INTRO = 'intro'
SUMMARY = 'sumario'
ROLLCALL = 'chamada'
ROLLCALL_PRESENT = 'chamada_presentes'
ROLLCALL_ABSENT = 'chamada_ausentes'
ROLLCALL_LATE = 'chamada_atrasados'
ROLLCALL_MISSION = 'chamada_missao'
SECTION = 'seccao'
END = 'fim'

MP_START = 'mp_inicio'
MP_CONT = 'continuacao'
CONT = 'continuacao'
OTHER_START = 'outro_inicio'
OTHER_CONT = 'outro_cont'

PRESIDENT_ASIDE = 'presidente_aparte'
PRESIDENT_NEWSPEAKER = 'presidente_temapalavra'
PRESIDENT_ROLLCALL = 'presidente_chamada'
PRESIDENT_OPEN = 'presidente_aberta'
PRESIDENT_CLOSE = 'presidente_encerrada'
PRESIDENT_SUSPEND = 'presidente_suspensa'
PRESIDENT_REOPEN = 'presidente_reaberta'
PRESIDENT_SWITCH = 'presidente_troca'

ORPHAN = 'orfao'

REAL_STATEMENTS = (MP_STATEMENT, GOV_STATEMENT, PRESIDENT_STATEMENT, VOICES_ASIDE, SECRETARY_STATEMENT, MP_CONT, PM_STATEMENT, MINISTER_STATEMENT, STATE_SECRETARY_STATEMENT, STATEMENT, MP_ASIDE, PRESIDENT_ASIDE, PRESIDENT_NEWSPEAKER, PRESIDENT_OPEN)
